name = "lapce-terraform-ls"
version = "0.0.1"
author = "panekj"
display-name = "Terraform (terraform-ls)"
description = "Terraform for Lapce: powered by hashicorp/terraform-ls"
wasm = "bin/lapce-terraform-ls.wasm"
